parameters:
    fp_js_form_validator.twig_extension.class: Fp\JsFormValidatorBundle\Twig\Extension\JsFormValidatorTwigExtension
    fp_js_form_validator.factory.class: Fp\JsFormValidatorBundle\Factory\JsFormValidatorFactory
    fp_js_form_validator.extension.class: Fp\JsFormValidatorBundle\Form\Extension\FormExtension

services:
    fp_js_form_validator.twig_extension:
        class: "%fp_js_form_validator.twig_extension.class%"
        arguments: ['@fp_js_form_validator.factory']
        tags: [{name: twig.extension}]

    fp_js_form_validator.extension:
        class: "%fp_js_form_validator.extension.class%"
        arguments: ["@fp_js_form_validator.factory"]
        tags: [{name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType}]

    fp_js_form_validator.factory:
        class: "%fp_js_form_validator.factory.class%"
        arguments:
            - "@validator"
            - "@translator"
            - "@router"
            - "%fp_js_form_validator.config%"
            - "%validator.translation_domain%"